---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-solr4
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-solr4
    name: {{ .Chart.Name }}-solr4
    common: solr4
spec:
  replicas: {{ .Values.replicas }}
#  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-solr4
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-solr4
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.sol.server6.name }}
      containers:
        - env:
            - name: JAVA_OPTS
              value: ' -Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.port=10074
-Dcom.sun.management.jmxremote.rmi.port=10074
-Dcom.sun.management.jmxremote.ssl=false
-Dfile.encoding=UTF-8
-Djava.rmi.server.hostname={{tpl .Values.global.clusterips.sol6.solr .}}
-Duser.language=ru
-Duser.timezone=Europe/Moscow
-Xms60G
-Xmx60G
-XX:+UnlockExperimentalVMOptions
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:G1MaxNewSizePercent=30
-XX:G1NewSizePercent=5
-XX:InitiatingHeapOccupancyPercent=60
-XX:MaxGCPauseMillis=500
-XX:ParallelGCThreads=12 '
            - name: ALFRESCO_SECURE_COMMS
              value: none
            - name: SOLR_ALFRESCO_HOST
              value: {{tpl .Values.global.clusterips.sol6.alfresco .}}
            - name: SOLR_ALFRESCO_PORT
              value: "8080"
            - name: SOLR_CREATE_ALFRESCO_DEFAULTS
              value: alfresco
            - name: SOLR_SOLR_HOST
              value: {{tpl .Values.global.clusterips.sol6.solr .}}
            - name: SOLR_SOLR_PORT
              value: "8080"
          image: {{ .Values.global.image.repository }}/solr4:{{ .Values.global.image.tag }}
          resources:
            limits:
              memory: "80G"
              cpu: "10"
            requests:
              memory: "20G"
              cpu: "10"
              ephemeral-storage: "128M"
          imagePullPolicy: "Always"
          livenessProbe:
            httpGet:
              path: /solr4
              port: 8080
            initialDelaySeconds: 15
            failureThreshold: 20
            periodSeconds: 15
            timeoutSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /solr4
#              port: 8080
#            initialDelaySeconds: 15
#            failureThreshold: 3
#            timeoutSeconds: 30
#            periodSeconds: 5
          name: {{ .Chart.Name }}-solr4
          ports:
            - containerPort: 8080
            - containerPort: 7777
            - containerPort: 10074
          stdin: true
          volumeMounts:
            - mountPath: /opt/infooborot/data
              name: sol-infodata
            - mountPath: /opt/tomcat8/logs
              name: sol-logs
#            - mountPath: /opt/infooborot/data/solr/workspace-SpacesStore/conf/solrcore.properties
#              name: {{ .Chart.Name }}-solorcore
#              subPath: {{ .Chart.Name }}-solorcore
#            - mountPath: /opt/tomcat8/webapps/solr4.war
#              name: solrw
#            - name: gw
#              mountPath: /opt/glowroot
            - mountPath: /etc/tomcat8/server.xml
              name: solr-serverxml
              subPath: solr-serverxml
            - mountPath: /opt/infooborot/data/solr/log4j-solr.properties
              name: solr-log4j-prop
              subPath: solr-log4j-prop
      restartPolicy: Always
      volumes:
        - name: solr-log4j-prop
          configMap:
            name: solr-log4j-prop
        - name: solr-serverxml
          configMap:
            name: solr-serverxml
        - name: {{ .Chart.Name }}-solorcore
          configMap:
            name: {{ .Chart.Name }}-solorcore
#        - name: solrw
#          hostPath:
#            path: /opt/mounts/solr4.war
#            type: File
#        - name: sol-infodata
#          persistentVolumeClaim:
#            claimName: {{ .Chart.Name }}-infodata
        - name: sol-infodata
          hostPath:
              path: /opt/infodatasolr4
              type: DirectoryOrCreate
        - name: sol-logs
          hostPath:
              path: /var/log/solr4
              type: DirectoryOrCreate
#        - name: sol-logs
#          persistentVolumeClaim:
#            claimName: {{ .Chart.Name }}-logs
#        - name: gw
#          persistentVolumeClaim:
#            claimName: {{ .Chart.Name }}-solr4-gw
      imagePullSecrets:
        - name: harbor-registry-secret
