---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-solr4
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-solr4
spec:
  clusterIP: "{{tpl .Values.global.clusterips.sol6.solr .}}"
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "7777"
    port: 7777
    targetPort: 7777
  - name: "10064"
    port: 10074
    targetPort: 10074
  selector:
    app: {{ .Chart.Name }}-solr4
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-{{ .Chart.Name }}-solr
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-solr4
spec:
  clusterIP: "{{tpl .Values.global.clusterips.sol6.solr_lb .}}"
  ports:
  - port: 8090
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}-solr4
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.nodes.sol.server6.ip}}"
  externalIPs: ["{{ .Values.global.nodes.sol.server6.ip}}"]
