apiVersion: v2
name: caukv2
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: app11
    version: ">=1.0.0"
    repository: file://../charts/app11
  - name: app12
    version: ">=1.0.0"
    repository: file://../charts/app12
  - name: app13
    version: ">=1.0.0"
    repository: file://../charts/app13
  - name: app14
    version: ">=1.0.0"
    repository: file://../charts/app14
  - name: sol11
    version: ">=1.0.0"
    repository: file://../charts/sol11
  - name: sol12
    version: ">=1.0.0"
    repository: file://../charts/sol12
  - name: sol13
    version: ">=1.0.0"
    repository: file://../charts/sol13
  - name: sol14
    version: ">=1.0.0"
    repository: file://../charts/sol14
  - name: addons
    version: ">=1.0.0"
    repository: file://../charts/addons
