---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.global.nfs.local.logcapacity }}
  claimRef:
    name: {{ .Chart.Name }}-logs
    namespace: {{ .Release.Namespace }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /var/log/solr4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.global.nodes.sol.server2.name }}
---
# PV CLAIMS DOWNWARDS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.nfs.local.logcapacity }}
  selector:
    matchLabels:
      pv: {{ .Chart.Name }}-logs
