kind: ConfigMap
metadata:
  name: solr-log4j-prop
  namespace: {{ .Release.Namespace }}
apiVersion: v1
data:
  solr-log4j-prop: |
    log4j.rootLogger=OFF, file
  solr-log4j-prop-off: |
    log4j.rootLogger=OFF, file
  solr-log4j-prop-on: |
    log4j.rootLogger=ERROR, Console, File
    log4j.appender.Console=org.apache.log4j.ConsoleAppender
    log4j.appender.Console.layout=org.apache.log4j.PatternLayout
    log4j.appender.Console.layout.ConversionPattern=%d{ISO8601} %x %-5p [%c{3}] [%t] %m%n
    log4j.appender.File=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.File.File=logs/solr.log
    log4j.appender.File.Append=true
    log4j.appender.File.DatePattern='.'yyyy-MM-dd
    log4j.appender.File.layout=org.apache.log4j.PatternLayout
    log4j.appender.File.layout.ConversionPattern=%d{yyyy-MM-dd} %d{ABSOLUTE} %-5p [%c] %m%n
    log4j.appender.TrackerFile=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.TrackerFile.File=logs/solr-tracker.log
    log4j.appender.TrackerFile.Append=true
    log4j.appender.TrackerFile.DatePattern='.'yyyy-MM-dd
    log4j.appender.TrackerFile.layout=org.apache.log4j.PatternLayout
    log4j.appender.TrackerFile.layout.ConversionPattern=%d{yyyy-MM-dd} %d{ABSOLUTE} %-5p [%c] %m%n
    log4j.logger.org.alfresco.solr.tracker.AbstractTracker=INFO, TrackerFile
    log4j.additivity.org.alfresco.solr.tracker.AbstractTracker=false
    log4j.appender.CacheWarmFile=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.CacheWarmFile.File=logs/solr-cache-warm.log
    log4j.appender.CacheWarmFile.Append=true
    log4j.appender.CacheWarmFile.DatePattern='.'yyyy-MM-dd
    log4j.appender.CacheWarmFile.layout=org.apache.log4j.PatternLayout
    log4j.appender.CacheWarmFile.layout.ConversionPattern=%d{yyyy-MM-dd} %d{ABSOLUTE} %-5p [%c] %m%n
    log4j.logger.org.apache.solr.search.SolrCache=ERROR, CacheWarmFile
    log4j.additivity.org.apache.solr.search.SolrCache=false
    log4j.appender.NodeCascadeFile=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.NodeCascadeFile.File=logs/solr-node-cascade.log
    log4j.appender.NodeCascadeFile.Append=true
    log4j.appender.NodeCascadeFile.DatePattern='.'yyyy-MM-dd
    log4j.appender.NodeCascadeFile.layout=org.apache.log4j.PatternLayout
    log4j.appender.NodeCascadeFile.layout.ConversionPattern=%d{yyyy-MM-dd} %d{ABSOLUTE} %-5p [%c] %m%n
    log4j.logger.org.alfresco.solr.tracker.MetadataTrackerStat=DEBUG, NodeCascadeFile
    log4j.additivity.org.alfresco.solr.tracker.MetadataTrackerStat=false
