apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-notification
  name: {{ .Chart.Name }}-notification
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-notification
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: cauk-apps
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.apps.server5.name }}
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
#        - image: {{ .Values.global.image.repository }}/notificationstore:{{ .Values.global.image.tag }}
        - image: {{ .Values.global.image.repository }}/notificationstore:cauk_latest
#          imagePullPolicy: "Always"
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh","-c"]
          args: ["source /vault/secrets/config && /opt/tomcat8/bin/catalina.sh run 2>&1 | /usr/bin/tee -a /opt/tomcat8/logs/catalina.out"]
          env:
            - name: DB_URL
              value: jdbc:postgresql://{{ .Values.global.databases.notification.server }}:5432/notificationstore
            - name: JAVA_OPTS
              value: ' -Duser.timezone=Europe/Moscow -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                       -Dcom.sun.management.jmxremote
                       -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.port=10085
                       -Dcom.sun.management.jmxremote.rmi.port=10085
                       -Dcom.sun.management.jmxremote.ssl=false
                       -Djava.rmi.server.hostname="{{tpl .Values.global.clusterips.addons.notification_jmx .}}"
                       -XX:-OmitStackTraceInFastThrow
                        -javaagent:/opt/glowroot/glowroot.jar
                        -Dglowroot.agent.id=cauk-adn-notif
                        -Dglowroot.collector.address=10.233.11.226:8181 '
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/notificationstore/
            failureThreshold: 20
            periodSeconds: 15
            timeoutSeconds: 20
          name: {{ .Chart.Name }}-notification
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "5G"
              cpu: "4"
              ephemeral-storage: "50G"
            requests:
              ephemeral-storage: "512M"
          volumeMounts:
            - name: gw
              mountPath: /opt/glowroot
            - name: addons-props
              mountPath: /opt/tomcat8/webapps/notificationstore/WEB-INF/classes/alfresco-global.properties
              subPath: no-addons-props
            - name: addons-props
              mountPath: /opt/tomcat8/conf/catalina.properties
              subPath: cata-props
            - name: addons-props
              mountPath: /opt/tomcat8/conf/server.xml
              subPath: no-serverxml
            - name: addons-props
              mountPath: /opt/tomcat8/conf/context.xml
              subPath: no-contextxml
            - name: addons-props
              mountPath: /opt/tomcat8/webapps/notificationstore/WEB-INF/classes/log4j.properties
              subPath: addons-notifica-log4j
            - mountPath: /opt/tomcat8/logs
              name: {{ .Release.Namespace }}-{{ .Chart.Name }}-notification
      restartPolicy: Always
      hostAliases:
      - ip: "{{tpl .Values.global.services.notification.server .}}"
        hostnames:
          - "postgres"
      volumes:
        - name: gw
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-notification-gw
        - name: addons-props
          configMap:
            name: addons-props
        - name: {{ .Release.Namespace }}-{{ .Chart.Name }}-notification
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-not-logs
    metadata:
      labels:
        service: {{ .Chart.Name }}-notification
      annotations:
        vault.hashicorp.com/namespace: 'vault'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cauk-apps'
        vault.hashicorp.com/agent-inject-secret-config: 'ksed/cauk/notdbauth'
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "ksed/cauk/notdbauth" -}}
           export NOT_DB_USER="{{ .Data.data.DBLOGIN }}"
           export NOT_DB_PASS="{{ .Data.data.DBPASS }}"
          {{- end }}`}}
