apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-exchangejournal
  name: {{ .Chart.Name }}-exchangejournal
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-exchangejournal
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: cauk-apps
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.apps.server5.name }}
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
#        - image: {{ .Values.global.image.repository }}/exchangejournal:2024.10.21
        - image: {{ .Values.global.image.repository }}/exchangejournal:{{ .Values.global.image.tag }}
#          imagePullPolicy: "Always"
          imagePullPolicy: "IfNotPresent"
#          command: ["/bin/sh","-c"]
#          args: ["source /vault/secrets/config && /opt/tomcat8/bin/catalina.sh run 2>&1 | /usr/bin/tee -a /opt/tomcat8/logs/catalina.out"]
          env:
            - name: JAVA_OPTS
              value: ' -Duser.timezone=Europe/Moscow -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80 
                        -Dcom.sun.management.jmxremote
                        -Dcom.sun.management.jmxremote.authenticate=false
                        -Dcom.sun.management.jmxremote.port=10084
                        -Dcom.sun.management.jmxremote.rmi.port=10084
                        -Dcom.sun.management.jmxremote.ssl=false
                        -Djava.rmi.server.hostname="{{tpl .Values.global.clusterips.addons.exchangejournal_jmx .}}"
                        -javaagent:/opt/glowroot/glowroot.jar
                        -Dglowroot.agent.id=cauk-adn-exch
                        -Dglowroot.collector.address=10.233.11.226:8181 '

#          livenessProbe:
#            exec:
#              command:
#                - curl
#                - -f
#                - http://localhost:8080/exchangejournal/rest/record?status==%27SENT%27
#            failureThreshold: 20
#            periodSeconds: 15
#            timeoutSeconds: 20
          name: {{ .Chart.Name }}-exchangejournal
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1024M"
          volumeMounts:
#            - name: addons-props
#              mountPath: /opt/tomcat8/shared/classes/alfresco-global.properties
#              subPath: addons-props
            - name: gw
              mountPath: /opt/glowroot
            - name: addons-props
              mountPath: /mount/tomcat8/webapps/exchangejournal/WEB-INF/classes/alfresco-global.properties
              subPath: ex-addons-props
            - name: addons-props
              mountPath: /mount/tomcat8/webapps/exchangejournal/WEB-INF/classes/logback.xml
              subPath: logback
            - name: addons-props
              mountPath: /opt/tomcat8/conf/catalina.properties
              subPath: cata-props
            - name: addons-props
              mountPath: /opt/tomcat8/conf/server.xml
              subPath: ex-serverxml
            - name: addons-props
              mountPath: /opt/tomcat8/conf/context.xml
              subPath: ex-contextxml
            - mountPath: /opt/tomcat8/logs
              name: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal
      restartPolicy: Always
      hostAliases:
      - ip: "{{tpl .Values.global.clusterips.addons.exchangejournal .}}"
        hostnames:
          - "postgres"
      volumes:
        - name: gw
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-exchangejournal-gw
        - name: addons-props
          configMap:
            name: addons-props
        - name: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-ex-logs
    metadata:
      labels:
        service: {{ .Chart.Name }}-exchangejournal
      annotations:
        vault.hashicorp.com/namespace: 'vault'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cauk-apps'
        vault.hashicorp.com/agent-inject-secret-config: 'ksed/cauk/exchdbauth'
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "ksed/cauk/exchdbauth" -}}
            export EX_DB_USER="{{ .Data.data.DBLOGIN }}"
            export EX_DB_PASS="{{ .Data.data.DBPASS }}"
          {{- end }}`}}
