apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-bj
  name: {{ .Chart.Name }}-bj
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-bj
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: cauk-apps
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.apps.server5.name }}
#        kubernetes.io/hostname: msk-edms-sol-15
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: {{ .Values.global.image.repository }}/businessjournal:{{ .Values.global.image.tag }}
#          imagePullPolicy: "Always"
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh","-c"]
          args: ["source /vault/secrets/config && /opt/tomcat8/bin/catalina.sh run 2>&1 | /usr/bin/tee -a /opt/tomcat8/logs/catalina.out"]
          env:
            - name: JAVA_OPTS
              value: ' -Duser.timezone=Europe/Moscow -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                       -Dcom.sun.management.jmxremote
                       -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.port=10086
                       -Dcom.sun.management.jmxremote.rmi.port=10086
                       -Dcom.sun.management.jmxremote.ssl=false
                       -Djava.rmi.server.hostname="{{tpl .Values.global.clusterips.addons.bj_jmx .}}"
                        -javaagent:/opt/glowroot/glowroot.jar
                        -Dglowroot.agent.id=cauk-adn-bj
                        -Dglowroot.collector.address=10.233.11.226:8181 '

          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/businessjournal
            failureThreshold: 20
            periodSeconds: 15
            timeoutSeconds: 20
          name: {{ .Chart.Name }}-bj
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: "1024M"
          volumeMounts:
#            - name: addons-props
#              mountPath: /opt/tomcat8/shared/classes/alfresco-global.properties
#              subPath: addons-props
            - name: gw
              mountPath: /opt/glowroot
            - name: addons-props
              mountPath: /opt/tomcat8/webapps/businessjournal/WEB-INF/classes/alfresco-global.properties
              subPath: bj-addons-props
            - name: addons-props
              mountPath: /opt/tomcat8/conf/catalina.properties
              subPath: cata-props
            - name: addons-props
              mountPath: /opt/tomcat8/conf/server.xml
              subPath: bj-serverxml
            - name: addons-props
              mountPath: /opt/tomcat8/conf/context.xml
              subPath: bj-contextxml
            - mountPath: /opt/tomcat8/logs
              name: {{ .Release.Namespace }}-{{ .Chart.Name }}-bj
      restartPolicy: Always
      hostAliases:
      - ip: "{{tpl .Values.global.clusterips.addons.bj .}}"
        hostnames:
          - "postgres"
      volumes:
        - name: gw
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-bj-gw
        - name: addons-props
          configMap:
            name: addons-props
        - name: {{ .Release.Namespace }}-{{ .Chart.Name }}-bj
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-bj-logs
    metadata:
      labels:
        service: {{ .Chart.Name }}-bj
      annotations:
        vault.hashicorp.com/namespace: 'vault'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cauk-apps'
        vault.hashicorp.com/agent-inject-secret-config: 'ksed/cauk/bjdbauth'
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "ksed/cauk/bjdbauth" -}}
          export BJ_DB_USER="{{ .Data.data.DBLOGIN }}"
          export BJ_DB_PASS="{{ .Data.data.DBPASS }}"
          {{- end }}`}}
