---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal
  labels:
    pv: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal
spec:
  capacity:
    storage: 5G
  claimRef:
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal
    namespace: {{ .Release.Namespace }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: {{ .Values.global.nfs.kubestore.basepath}}{{ .Chart.Name }}/exchangejournal/logs
    server: {{ .Values.global.nfs.kubestore.server}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-exchangejournal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: nfs
  selector:
    matchLabels:
      pv: {{ .Release.Namespace }}-{{ .Chart.Name }}-exchangejournal

status: {}
