---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-exchangejournal
  name: {{ .Chart.Name }}-exchangejournal
spec:
  clusterIP: "{{tpl .Values.global.clusterips.addons.exchangejournal .}}"
  ports:
    - name: "8780"
      port: 8780
      targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-exchangejournal
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-{{ .Chart.Name }}-exchangejournal
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-exchangejournal
spec:
  clusterIP: "{{tpl .Values.global.clusterips.addons.exchangejournal_lb .}}"
  ports:
  - port: 8780
    targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-exchangejournal
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.nodes.apps.server5.ip}}"
  externalIPs: ["{{ .Values.global.nodes.apps.server5.ip}}"]
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-exchangejournal
  name: {{ .Chart.Name }}-exchangejournal-jmx
spec:
  clusterIP: "{{tpl .Values.global.clusterips.addons.exchangejournal_jmx .}}"
  ports:
    - name: "10084"
      port: 10084
      targetPort: 10084
  selector:
    service: {{ .Chart.Name }}-exchangejournal
status:
  loadBalancer: {}
