---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-notification
  name: {{ .Chart.Name }}-notification
spec:
  clusterIP: "{{tpl .Values.global.clusterips.addons.notification .}}"
  ports:
    - name: "8680"
      port: 8680
      targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-notification
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-{{ .Chart.Name }}-notification
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-notification
spec:
  clusterIP: "{{tpl .Values.global.clusterips.addons.notification_lb .}}"
  ports:
  - port: 8680
    targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-notification
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.nodes.apps.server5.ip}}"
  externalIPs: ["{{ .Values.global.nodes.apps.server5.ip}}"]
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-notification
  name: {{ .Chart.Name }}-notification-jmx
spec:
  clusterIP: "{{tpl .Values.global.clusterips.addons.notification_jmx .}}"
  ports:
    - name: "10085"
      port: 10085
      targetPort: 10085
  selector:
    service: {{ .Chart.Name }}-notification
status:
  loadBalancer: {}
