---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-ild
  name: {{ .Chart.Name }}-ild
spec:
  clusterIP: "{{tpl .Values.global.clusterips.app4.ild .}}"
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-ild
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-{{ .Chart.Name }}-ild
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-ild
spec:
  ports:
  - port: 8380
    targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-ild
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.global.nodes.apps.server4.ip}}"
  externalIPs: ["{{ .Values.global.nodes.apps.server4.ip}}"]
