apiVersion: v1
data:
  hazelcast-tcp: |
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
      <group>
          <name>repo</name>
          <password>alfresco</password>
      </group>
      <management-center enabled="false"></management-center>
      <network>
          <public-address>10.233.10.213</public-address>
          <port auto-increment="true" port-count="100">5701</port>
          <outbound-ports>
            <ports>33000-35000</ports>
            <ports>37000,37001,37002,37003</ports>
            <ports>38000,38500-38600</ports>
        </outbound-ports>
          <join>
             <multicast enabled="false">
              <multicast-group>224.2.2.3</multicast-group>
              <multicast-port>54327</multicast-port>
             </multicast>
             <tcp-ip enabled="false">
              <member-list>
              </member-list>
           </tcp-ip>
            <kubernetes enabled="false">
                    <namespace>cauk</namespace>
                    <servicename>hazelcast</servicename>
            </kubernetes>
          </join>
          <interfaces enabled="true">
            <interface>10.233.*.*</interface>
          </interfaces>
      </network>
      <map name="default">
          <backup-count>1</backup-count>
          <time-to-live-seconds>0</time-to-live-seconds>
          <eviction-policy>LRU</eviction-policy>
          <eviction-percentage>25</eviction-percentage>
          <merge-policy>ExpirationTimeMergePolicy</merge-policy>
      </map>
      <map name="AlfrescoFilesysCache">
          <backup-count>1</backup-count>
          <eviction-policy>NONE</eviction-policy>
          <max-size>0</max-size>
          <eviction-percentage>25</eviction-percentage>
          <merge-policy>ExpirationTimeMergePolicy</merge-policy>
      </map>
      <map name="lockStore">
          <backup-count>1</backup-count>
          <eviction-policy>NONE</eviction-policy>
          <eviction-percentage>0</eviction-percentage>
          <merge-policy>ExpirationTimeMergePolicy</merge-policy>
          <max-size>0</max-size>
          <time-to-live-seconds>172800</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
      </map>
      <properties>
        <property name="hazelcast.logging.type">log4j</property>
        <property name="hazelcast.rest.enabled">false</property>
        <property name="hazelcast.memcache.enabled">false</property>
        <property name="hazelcast.max.operation.timeout">20000</property>
        <property name="hazelcast.max.no.heartbeat.seconds">60</property>
        <property name="hazelcast.socket.bind.any">true</property>
      </properties>
    </hazelcast>
kind: ConfigMap
metadata:
  name: app15-hazelcast
  namespace: cauk
