---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-cstore-deleted
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.global.nfs.local.capacity }}
#    storage: "50G"
  claimRef:
    name: {{ .Chart.Name }}-cstore-deleted
    namespace: {{ .Release.Namespace }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /opt/contentstore.deleted
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.global.nodes.apps.server5.name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-cscache
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.global.nfs.local.capacity }}
#    storage: "50G"
  claimRef:
    name: {{ .Chart.Name }}-cscache
    namespace: {{ .Release.Namespace }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /opt/cachedcontent
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.global.nodes.apps.server5.name }}
---
# PV CLAIMS DOWNWARDS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-cstore-deleted
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.nfs.local.capacity }}
#      storage: "50G"
  selector:
    matchLabels:
      pv: {{ .Chart.Name }}-cstore-deleted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-cscache
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.nfs.local.capacity }}
#      storage: "50G"
  selector:
    matchLabels:
      pv: {{ .Chart.Name }}-cscache
