---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-alfresco
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-alfresco
    name: {{ .Chart.Name }}-alfresco
#    common: solr4
spec:
  replicas: {{ .Values.replicas }}
#  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-alfresco
      name: {{ .Chart.Name }}-alfresco
  template:
    spec:
      serviceAccountName: cauk-apps
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.sol.server5.name }}
      containers:
      - image: {{ .Values.global.image.repository }}/alfresco:{{ .Values.global.image.tag }}
        command: ["/opt/tomcat8/bin/substituter.sh", "/opt/tomcat8/bin/catalina.sh run 2>&1 | /usr/bin/tee -a /opt/tomcat8/logs/catalina.out"]
        env:
        - name: JAVA_OPTS
          value: ' -Dcom.sun.management.jmxremote
                   -Dcom.sun.management.jmxremote.authenticate=false
                   -Dcom.sun.management.jmxremote.port=10054
                   -Dcom.sun.management.jmxremote.rmi.port=10054
                   -Dcom.sun.management.jmxremote.ssl=false
                   -Ddeployment.method=DOCKER_COMPOSE
                   -Dfile.encoding=UTF-8
                   -Djavax.servlet.request.encoding=UTF-8
                   -Djava.net.preferIPv4Addresses=true
                   -Djava.rmi.server.hostname={{tpl .Values.global.clusterips.sol5.alfresco .}}
                   -Dlegacy.transform.service.enabled=true
                   -Dlocal.transform.service.enabled=true
                   -Dmessaging.broker.url="vm://localhost?brokerConfig=xbean:alfresco/subsystems/Messaging/default/activemq/activemq.xml"
                   -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*
                   -Dtransform.service.enabled=false
                   -Duser.language=ru
                   -Duser.timezone=Europe/Moscow
                   -Xms100g
                   -Xmx100g
                   -XshowSettings:vm
                   -XX:+UseContainerSupport
                   -XX:+UseG1GC
                   -XX:MaxRAMPercentage=90
                   -javaagent:/opt/glowroot/glowroot.jar
                   -Dglowroot.agent.id=nt-alfresco-{{ .Chart.Name }}
                   -Dglowroot.collector.address=10.233.11.226:8181 '
        imagePullPolicy: "Always"
        livenessProbe:
         tcpSocket:
           port: 8080
         initialDelaySeconds: 2400
         failureThreshold: 3
         timeoutSeconds: 30
         periodSeconds: 30
        readinessProbe:
         httpGet:
           path: /alfresco
           port: 8080
         initialDelaySeconds: 15
         failureThreshold: 3
         timeoutSeconds: 30
         periodSeconds: 5
        name: {{ .Chart.Name }}-alfresco
        ports:
        - containerPort: 8080
        - containerPort: 10054
        resources:
          limits:
            cpu: "10"
            memory: "120G"
        volumeMounts:
          - name: cstore-deleted
            mountPath: /opt/infooborot/alf_data/contentstore.deleted
          - name: cstore
            mountPath: /opt/infooborot/alf_data/contentstore
          - name: cstore2017
            mountPath: /opt/infooborot/alf_data/contentstore/2017
          - name: cstore2018
            mountPath: /opt/infooborot/alf_data/contentstore/2018
          - name: cstore2019
            mountPath: /opt/infooborot/alf_data/contentstore/2019
          - name: cstore2020
            mountPath: /opt/infooborot/alf_data/contentstore/2020
          - name: cstore2021
            mountPath: /opt/infooborot/alf_data/contentstore/2021
          - name: cstore2022
            mountPath: /opt/infooborot/alf_data/contentstore/2022
          - name: cscache
            mountPath: /opt/infooborot/alf_data/cachedcontent
          - name: shared
            mountPath: /opt/tomcat8/shared
#          - name: java11
#            mountPath: /opt/java11
          - name: keystore
            mountPath: /opt/keystore
          - name: logs
            mountPath: /opt/tomcat8/logs
          - name: serverxml
            mountPath: /opt/tomcat8/conf/server.xml
            subPath: serverxml
          - name: serverxml
            mountPath: /opt/tomcat8/conf/context.xml
            subPath: contextxml
          - name: serverxml
            mountPath: /opt/tomcat8/conf/catalina.properties
            subPath: catalinaprop
          - name: lic
            mountPath: /opt/tomcat8/shared/classes/license.lic
            subPath: lic
            readOnly: true
          - name: lecmlicense
            mountPath: /opt/tomcat8/shared/classes/lecmlicense
            subPath: lecmlicense
            readOnly: true
          - name: gw
            mountPath: /opt/glowroot
#          - name: repo
#            mountPath: /mount/tomcat8/webapps/alfresco/WEB-INF/lib/alfresco-repository-7.199.0m.jar
      restartPolicy: Always
      hostname: {{ .Values.global.nodes.sol.server5.name }}
      volumes:
      - name: cstore-deleted
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-cstore-deleted
      - name: cstore
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore
      - name: cstore2017
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2017
      - name: cstore2018
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2018
      - name: cstore2019
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2019
      - name: cstore2020
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2020
      - name: cstore2021
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2021
      - name: cstore2022
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2022
      - name: cscache
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-cscache
      - name: shared
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-alfresco
      - name: java11
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-java11
      - name: keystore
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-keystore
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-alf-logs
      - name: gw
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-alfresco-gw
      ### configmaps
      - name: serverxml
        configMap:
          name: serverxml
      ### secrets
      - name: lecmlicense
        secret:
          secretName: licenses
      - name: lic
        secret:
          secretName: licenses
     ### Local Large
      - name: repo
        hostPath:
          path: /opt/mounts/alfresco-repository-7.199.0m.jar
          type: File
      imagePullSecrets:
        - name: harbor-registry-secret
    metadata:
      labels:
        app: {{ .Chart.Name }}-alfresco
        name: {{ .Chart.Name }}-alfresco
      annotations:
        vault.hashicorp.com/namespace: 'vault'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cauk-apps'
        vault.hashicorp.com/agent-inject-secret-config: 'ksed/cauk/app2'
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "ksed/cauk/app2" -}}
          export DB_USER="{{ .Data.data.dbm_USER }}"
          export DB_PASS="{{ .Data.data.dbm_PASS }}"
          export DBR_USER="{{ .Data.data.dbr_USER }}"
          export DBR_PASS="{{ .Data.data.dbr_PASS }}"
          export LDAP_USER="{{ .Data.data.ldap_USER }}"
          export LDAP_PASS="{{ .Data.data.ldap_PASS }}"
          export FED_USER="{{ .Data.data.fed_USER }}"
          export FED_PASS="{{ .Data.data.fed_PASS }}"
          export PMI_USER="{{ .Data.data.pmi_USER }}"
          export PMI_PASS="{{ .Data.data.pmi_PASS }}"
          export INIT_ADMIN_PASS="{{ .Data.data.admin_init_PASS }}"
          export KRB_PASS="{{ .Data.data.krb_PASS }}"
          {{- end }}`}}
