apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-ild-props
  namespace: {{ .Release.Namespace }}
data:
  ild-props: |-
    spring.main.banner-mode=off
    spring.jpa.database=POSTGRESQL
    spring.jpa.show-sql=false
    spring.database.driverClassName=org.postgresql.Driver
    spring.datasource.url=jdbc:postgresql://{{ .Values.global.databases.bj.server }}:5432/ild_cauk_db?targetServerType=master
    spring.datasource.username=ild_user
    spring.datasource.password=ildpass
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.platform=postgres
    logging.config=config/log4j2-spring.xml

    spring.datasource.hikari.minimumIdle=5
    spring.datasource.hikari.maximumPoolSize=10
    spring.datasource.hikari.idleTimeout=30000
    spring.datasource.hikari.maxLifetime=120000
    spring.datasource.hikari.connectionTimeout=300000

    server.port=8080

    ild.role.user=ild_users
    ild.role.secretary=ild_secretaries
    ild.role.officer=ild_officers
    ild.role.admin=ild_admins

    ild.system.password=password
    ild.rest-storage.url=http://{{ .Chart.Name }}-alfresco:8080
    ild.title-page=false

    logbook.write.level=DEBUG
    logbook.write.category=ru.everytag.ild.Controller
    logbook.filter.enabled=true

    spring.servlet.multipart.max-file-size=100MB
    spring.servlet.multipart.max-request-size=100MB

  log4j: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO">
        <Properties>
            <Property name="PID">????</Property>
            <Property name="LOG_EXCEPTION_CONVERSION_WORD">%xwEx</Property>
            <Property name="LOG_LEVEL_PATTERN">%5p</Property>
            <Property name="CONSOLE_LOG_PATTERN">%clr{%d{yyyy-MM-dd HH:mm:ss.SSS}}{faint} %clr{${LOG_LEVEL_PATTERN}} %clr{${sys:PID}}{magenta} %clr{---}{faint} %clr{[%15.15t]}{faint} %clr{%-40.40c{1.}}{cyan} %clr{:}{faint} %m%n${sys:LOG_EXCEPTION_CONVERSION_WORD}</Property>
            <Property name="FILE_LOG_PATTERN">%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN} ${sys:PID} --- [%t] %-40.40c{1.} : %m%n${sys:LOG_EXCEPTION_CONVERSION_WORD}</Property>
        </Properties>
        <Appenders>
            <Console name="STDOUT" target="SYSTEM_OUT" ignoreExceptions="false">
                <PatternLayout pattern="${sys:CONSOLE_LOG_PATTERN}"/>
            </Console>
            <RollingFile name="RollingFile" fileName="/var/log/ild.log"
                         filePattern="/var/log/$${date:yyyy-MM}/ild-%d{MM-dd-yyyy}-%i.log">
                <PatternLayout pattern="${sys:FILE_LOG_PATTERN}"/>
                <Policies>
                    <OnStartupTriggeringPolicy/>
                    <TimeBasedTriggeringPolicy/>
                    <SizeBasedTriggeringPolicy size="1 MB"/>
                </Policies>
            </RollingFile>
        </Appenders>
        <Loggers>
    	<Root level="DEBUG">
                <AppenderRef ref="RollingFile"/>
                <AppenderRef ref="STDOUT" level="info"/>
            </Root>
            <Logger name="ru.everytag.ild">
                <AppenderRef ref="RollingFile"/>
                <AppenderRef ref="STDOUT" level="debug"/>
            </Logger>
        </Loggers>
    </Configuration>
