---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-alfresco
  namespace: {{ .Release.Namespace }}
  labels:
    app: alfresco
    name: {{ .Chart.Name }}-alfresco
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alfresco
      name: {{ .Chart.Name }}-alfresco
  template:
    spec:
      hostAliases:
          - hostnames:
            - "rosneft.ru"
            - "domaindnszones.rosneft.ru"
            - "forestdnszones.rosneft.ru"
            ip: "10.20.6.160"
          - hostnames:
            - "rosneft.ru"
            - "domaindnszones.rosneft.ru"
            - "forestdnszones.rosneft.ru"
            ip: "10.20.6.161"
      hostname: {{ .Values.global.nodes.apps.server2.name }}
      imagePullSecrets:
       - name: harbor-registry-secret
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.apps.server2.name }}
      restartPolicy: Always
      serviceAccountName: cauk-apps
      containers:
      - image: {{ .Values.global.image.repository }}/alfresco:{{ .Values.global.image.tag }}
        imagePullPolicy: Always
        command: ["/opt/tomcat8/bin/substituter.sh", "/opt/tomcat8/bin/catalina.sh run 2>&1 | /usr/bin/tee -a /opt/tomcat8/logs/catalina.out"]
        env:
        - name: JAVA_OPTS
          value: ' --add-modules java.se
            --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
            --add-opens java.base/java.lang=ALL-UNNAMED
            --add-opens java.base/java.nio=ALL-UNNAMED
            --add-opens java.base/sun.nio.ch=ALL-UNNAMED
            --add-opens java.management/sun.management=ALL-UNNAMED
            --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.port=10054
            -Dcom.sun.management.jmxremote.rmi.port=10054
            -Dcom.sun.management.jmxremote.ssl=false
            -Dfile.encoding=UTF-8
            -Djavax.servlet.request.encoding=UTF-8
            -Dhazelcast.diagnostics.enabled=true
            -DjvmRoute=msk-edms-app-12
            -Djava.net.preferIPv4Addresses=true
            -Djava.rmi.server.hostname={{tpl .Values.global.clusterips.app2.alfresco .}}
            -Dlegacy.transform.service.enabled=true
            -Dlocal.transform.service.enabled=true
            -Dmessaging.broker.ssl=false
            -Dmessaging.broker.url="failover:(nio://{{tpl .Values.global.clusterips.app2.activemq .}}:61616)?timeout=3000&jms.useCompression=true"
            -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*
            -Dtransform.service.enabled=false
            -Duser.language=ru
            -Duser.timezone=Europe/Moscow
            -Xms{{ default 90 .Values.xms }}g
            -Xmx{{ default 90 .Values.xmx }}g
            -XX:MaxRAMPercentage=90
            -XX:MinRAMPercentage=50
            -javaagent:/opt/glowroot/glowroot.jar
            -Dglowroot.agent.id=nt-alfresco-12
            -Dglowroot.collector.address=10.233.11.226:8181'
        - name: KERBEROS_ENABLED
          value: 'true'
        - name: KERBEROS_REALM
          value: 'ROSNEFT.RU'
        - name: KERBEROS_SPN
          value: 'ksed.rosneft.ru@ROSNEFT.RU'
        - name: KERBEROS_KEYTAB
          value: 'httpksed.keytab'
        - name: KERBEROS_PRINCIPAN
          value: 'ksed.rosneft.ru'
        - name: KERBEROS_ADMIN_USER_NAMES
          value: 'admin'
        livenessProbe:
         tcpSocket:
           port: 8080
         initialDelaySeconds: 60
         failureThreshold: 3
         timeoutSeconds: 30
         periodSeconds: 30
        readinessProbe:
         httpGet:
           path: /alfresco
           port: 8080
         initialDelaySeconds: 15
         failureThreshold: 3
         timeoutSeconds: 30
         periodSeconds: 5
        name: {{ .Chart.Name }}-alfresco
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 10054
        resources:
          limits:
            memory: {{ default "110G" .Values.mem }}
            cpu: {{ default "9" .Values.cpu }}
            #ephemeral-storage: "30G"
          requests:
            ephemeral-storage: "10G"
        volumeMounts:
          - name: cstore-deleted
            mountPath: /opt/infooborot/alf_data/contentstore.deleted
          - name: cstore
            mountPath: /opt/infooborot/alf_data/contentstore
          - name: cstore2017
            mountPath: /opt/infooborot/alf_data/contentstore/2017
          - name: cstore2018
            mountPath: /opt/infooborot/alf_data/contentstore/2018
          - name: cstore2019
            mountPath: /opt/infooborot/alf_data/contentstore/2019
          - name: cstore2020
            mountPath: /opt/infooborot/alf_data/contentstore/2020
          - name: cstore2021
            mountPath: /opt/infooborot/alf_data/contentstore/2021
          - name: cstore2022
            mountPath: /opt/infooborot/alf_data/contentstore/2022
          - name: cscache
            mountPath: /opt/infooborot/alf_data/cachedcontent
          - name: shared
            mountPath: /opt/tomcat8/shared
          - name: keystore
            mountPath: /opt/keystore/ssl.keystore
            subPath: keystore
          - name: keystore
            mountPath: /opt/keystore/ssl.truststore
            subPath: truststore
          - name: confdir
            mountPath: /opt/tomcat8/conf
          - name: logs
            mountPath: /opt/tomcat8/logs
          - name: serverxml
            mountPath: /opt/tomcat8/conf/server.xml
            subPath: serverxml
          - name: serverxml
            mountPath: /opt/tomcat8/conf/context.xml
            subPath: contextxml
          - name: serverxml
            mountPath: /opt/tomcat8/conf/catalina.properties
            subPath: catalinaprop
          - name: lic
            mountPath: /opt/infooborot/license.lic
            subPath: lic
            readOnly: true
          - name: mounts
            mountPath: /etc/krb5.conf
            subPath: krb
          - name: mounts
            mountPath: /etc/httpksed.keytab
            subPath: keytab
          - name: lecmlicense
            mountPath: /opt/tomcat8/shared/classes/lecmlicense
            subPath: lecmlicense
            readOnly: true
          - name: webconfcustxml
            mountPath: /opt/tomcat8/shared/classes/alfresco/extension/web-scripts-config-custom.xml
            subPath: webconfcustxml2
            readOnly: true
          - name: secret-files
            subPath: kerb-filt-prop
            mountPath: /opt/tomcat8/shared/classes/kerberos-filter.properties
            readOnly: true
          - name: secret-files
            subPath: kerb-filt-prop
            mountPath: /opt/tomcat8/shared/classes/alfresco/extension/subsystems/Authentication/kerberos/Kerberos1/kerberos-filter.properties
            readOnly: true
          - name: secret-files
            subPath: shar-conf-cust
            mountPath: /opt/tomcat8/shared/classes/alfresco/web-extension/share-config-custom.xml_SSO
            readOnly: true
          - name:  hazelcast
            subPath: hazelcast-tcp
            mountPath: /opt/tomcat8/shared/classes/alfresco/extension/hazelcast-tcp.xml
          - name: secret-files
            subPath: glrt-agnt-conf
            mountPath: /opt/glowroot/config.json
            readOnly: true
          - name: gw
            mountPath: /opt/glowroot
#          - name: webapps-alfresco
#            mountPath: /mount/tomcat8/webapps/alfresco/WEB-INF/classes/alfresco/module/lecm-security-repo/extension-context/security-extension-service-context.xml
#            subPath: secex
          - name: agp
            mountPath: /opt/tomcat8/shared/classes/alfresco-global.properties
            subPath: alfresco-global.properties
          - name: alfrepo
            mountPath: /mount/tomcat8/webapps/alfresco/WEB-INF/lib/lecm-repo-override-2.0-SNAPSHOT.jar
#          - name: sqlmap
#            mountPath: /mount/tomcat8/webapps/alfresco/WEB-INF/classes/alfresco/ibatis/alfresco-SqlMapConfig.xml 
#          - name: valid
#            mountPath: /mount/tomcat8/webapps/alfresco/WEB-INF/classes/alfresco/templates/webscripts/ru/it/lecm/lnd/document/validation.lib.js
      volumes:
      - name: cstore-deleted
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-cstore-deleted
      - name: cstore
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore
      - name: cstore2017
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2017
      - name: cstore2018
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2018
      - name: cstore2019
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2019
      - name: cstore2020
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2020
      - name: cstore2021
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2021
      - name: cstore2022
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-cstore2022
      - name: cscache
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-cscache
      - name: shared
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-alfresco
#      - name: keystore
#        persistentVolumeClaim:
#          claimName: {{ .Release.Namespace }}-keystore
      - name: confdir
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-confdir
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-alf-logs
      ### configmaps
      - name: serverxml
        configMap:
          name: serverxml
      - name: webconfcustxml
        configMap:
          name: webconfcustxml2
      - name: mounts
        configMap:
          name: mounts
      - name: webapps-alfresco
        configMap:
          name: webapps-alfresco
      - name: webapps-alfresco2
        configMap:
          name: webapps-alfresco2
      - name: webapps-alfresco3
        configMap:
          name: webapps-alfresco3
      - name: hazelcast
        configMap:
          name: {{ .Chart.Name}}-hazelcast
      - name: agp
        configMap:
          name: {{ .Release.Namespace }}-{{ .Chart.Name }}-configmaps
      ### secrets
      - name: keystore
        secret:
          secretName: ssl
      - name: secret-files
        secret:
          secretName: secret-files
      - name: lecmlicense
        secret:
          secretName: licenses
      - name: lic
        secret:
          secretName: licenses
#      - name: groovy
#        hostPath:
#          path: /home/rosneft.ru/dngaraev_adm_skp/groovy-all-2.4.10.jar
#          type: File    
      - name: repo
        hostPath:
          path: /opt/mounts/lecm-repo-override-2.0-SNAPSHOT.jar
          type: File
      - name: gw
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-alfresco-gw
      - name: alfrepo
        hostPath:
          path: /opt/mounts/25042025/alfresco/lecm-repo-override-2.0-SNAPSHOT.jar
          type: File
    metadata:
      labels:
        app: alfresco
        name: {{ .Chart.Name }}-alfresco
      annotations:
        vault.hashicorp.com/namespace: 'vault'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cauk-apps'
        vault.hashicorp.com/agent-inject-secret-config: 'ksed/cauk/app2'
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "ksed/cauk/app2" -}}
          export DB_USER="{{ .Data.data.dbm_USER }}"
          export DB_PASS="{{ .Data.data.dbm_PASS }}"
          export DBR_USER="{{ .Data.data.dbr_USER }}"
          export DBR_PASS="{{ .Data.data.dbr_PASS }}"
          export LDAP_USER="{{ .Data.data.ldap_USER }}"
          export LDAP_PASS="{{ .Data.data.ldap_PASS }}"
          export FED_USER="{{ .Data.data.fed_USER }}"
          export FED_PASS="{{ .Data.data.fed_PASS }}"
          export PMI_USER="{{ .Data.data.pmi_USER }}"
          export PMI_PASS="{{ .Data.data.pmi_PASS }}"
          export INIT_ADMIN_PASS="{{ .Data.data.admin_init_PASS }}"
          export KRB_PASS="{{ .Data.data.krb_PASS }}"
          export KERBEROS_SECRET="{{ .Data.data.krb_PASS }}"
          export TS_PASS="{{ .Data.data.ts_PASS }}"
          export KS_PASS="{{ .Data.data.ks_PASS }}"
          {{- end }}`}}
