---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Chart.Name }}-ild
  name: {{ .Chart.Name }}-ild
spec:
  clusterIP: "{{tpl .Values.global.clusterips.app2.ild .}}"
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-ild
status:
  loadBalancer: {}
