---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-share
  namespace: {{ .Release.Namespace }}
  labels:
    app: share
    name: {{ .Chart.Name }}-share
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: share
      name: {{ .Chart.Name }}-share
  template:
    spec:
      hostname: {{ .Values.global.nodes.apps.server6.name }}
      imagePullSecrets:
        - name: harbor-registry-secret
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.nodes.apps.server6.name }}
      restartPolicy: Always
      serviceAccountName: cauk-apps
      containers:
      - image: {{ .Values.global.image.repository }}/share:{{ .Values.global.image.tag }}
#      - image: {{ .Values.global.image.repository }}/share:4.7.2_2024.09.27
        imagePullPolicy: Always
        command: ["/opt/tomcat8/shared/classes/alfresco/substituter.sh", "/opt/tomcat8/bin/catalina.sh run 2>&1 | /usr/bin/tee -a /opt/tomcat8/logs/catalina.out"]
        env:
        - name: JAVA_OPTS
          value: '
            -Dalfresco.context=alfresco
            -Dalfresco.host=alfresco
            -Dalfresco.port=8080
            -Dalfresco.protocol=http
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.port=10064
            -Dcom.sun.management.jmxremote.rmi.port=10064
            -Dcom.sun.management.jmxremote.ssl=false
            -Djava.rmi.server.hostname={{tpl .Values.global.clusterips.app6.share_jmx .}}
            -DjvmRoute=app-16
            -Duser.timezone=Europe/Moscow
            -Xms{{ default 16 .Values.sxms }}g
            -Xmx{{ default 16 .Values.sxmx }}g
            -Dfile.encoding=UTF-8
            -Djavax.servlet.request.encoding=UTF-8
            -XX:MaxRAMPercentage=90
            -XX:MinRAMPercentage=50
            -javaagent:/opt/glowroot/glowroot.jar
            -Dglowroot.agent.id=nt-share-16
            -Dglowroot.collector.address=10.233.11.226:8181 '
        - name: KERBEROS_ENABLED
          value: 'true'
        - name: KERBEROS_SECRET
          value: 'XSW@zaq112HFA5arDF%6esdfadb@#de27'
        - name: KERBEROS_REALM
          value: 'ROSNEFT.RU'
        - name: KERBEROS_SPN
          value: 'ksed.rosneft.ru@ROSNEFT.RU'
        - name: KERBEROS_KEYTAB
          value: 'httpksed.keytab'
        - name: KERBEROS_PRINCIPAN
          value: 'ksed.rosneft.ru'
        - name: KERBEROS_ADMIN_USER_NAMES
          value: 'admin'
        - name: REPO_HOST
          value: "{{tpl .Values.global.clusterips.app6.alfresco .}}"
        - name: REPO_PORT
          value: "8080"
        livenessProbe:
         tcpSocket:
           port: 8080
         initialDelaySeconds: 30
         failureThreshold: 3
         timeoutSeconds: 15
         periodSeconds: 5
#        readinessProbe:
#         httpGet:
#           path: /share/page
#           port: 8080
#           httpHeaders:
#            - name: Authorization
#              value: Basic YWRtaW46THR5dHV5dG4/eWpkc2x0aDtibnRjbQ==
#         initialDelaySeconds: 5
#         failureThreshold: 3
#         timeoutSeconds: 5
#         periodSeconds: 5
        name: {{ .Chart.Name }}-share
        ports:
        - containerPort: 8080
        - containerPort: 8543
        - containerPort: 10064
#        resources:
#          limits:
#            memory: {{ default "20G" .Values.smem }}
#            memory: "25G"
#            cpu: {{ default "3" .Values.xcpu }}
#            #ephemeral-storage: "30G"
#          requests:
#            ephemeral-storage: "10G"
        volumeMounts:
#          - name: share
#            subPath: share_webxml
#            mountPath: /opt/tomcat8/conf/web.xml
#          - name: keystore
#            mountPath: /opt/infooborot/alf_data/keystore
          - name: keystore
            mountPath: /opt/infooborot/alf_data/keystore/ssl.keystore
            subPath: keystore
          - name: keystore
            mountPath: /opt/infooborot/alf_data/keystore/ssl.truststore
            subPath: truststore
          - name: share
            mountPath: /opt/tomcat8/conf/catalina.properties
            subPath: catalinaprop
          - name: share
            mountPath: /opt/tomcat8/conf/server.xml
            subPath: share_serverxml
          - name: share
            mountPath: /opt/tomcat8/conf/context.xml
            subPath: share_contextxml
          - name: mounts
            mountPath: /mount/tomcat8/webapps/ROOT.war
            subPath: rootwar
          - name: mountroot
            mountPath: /mount/tomcat8/webapps/ROOT
          - name: gw
            mountPath: /opt/glowroot
          - name: logs
            mountPath: /opt/tomcat8/logs
          - name: mounts
            mountPath: /etc/krb5.conf
            subPath: krb
          - name: mounts
            mountPath: /etc/httpksed.keytab
            subPath: keytab
#          - name: webapps-share
#            mountPath: /mount/tomcat8/webapps/share/scripts/lecm-internal/change-fields-availability.js
#            subPath: change-fields-availability
#          - name: webapps-share
#            mountPath: /mount/tomcat8/webapps/share/scripts/lecm-internal/change-fields-availability-min.js
#            subPath: change-fields-availability-min
          - name: mounts
            mountPath: /mount/tomcat8/webapps/share/js/lib/logic_ecm/notifications/NotificationsPopup.js
            subPath: notif
          - name: mounts
            mountPath: /mount/tomcat8/webapps/share/js/lib/logic_ecm/notifications/NotificationsPopup-min.js
            subPath: notifmin
#          - name: mounts
#            mountPath: /mount/tomcat8/webapps/share/js/lib/logic_ecm/notifications/RnNotificationsPopup.js
#            subPath: rnnotif
#          - name: mounts
#            mountPath: /mount/tomcat8/webapps/share/js/lib/logic_ecm/notifications/RnNotificationsPopup-min.js
#            subPath: rnnotifmin
#          - name: mounts
#            mountPath: /mount/tomcat8/webapps/share/scripts/lecm-eds-documents/execution-tree-control.js
#            subPath: execution_tree_control_js
#          - name: mounts
#            mountPath: /mount/tomcat8/webapps/share/scripts/lecm-eds-documents/execution-tree-control-min.js
#            subPath: execution_tree_control_min_js
          - name: secret-files
            subPath: glrt-agnt-conf
            mountPath: /opt/glowroot/config.json
            readOnly: true
          - name: atb
            mountPath: /mount/tomcat8/webapps/share/scripts/lecm-base/components/activiti-transitions-buttons-digital-signature.js
          - name: atb-min
            mountPath: /mount/tomcat8/webapps/share/scripts/lecm-base/components/activiti-transitions-buttons-digital-signature-min.js
      volumes:
      - name: gw
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-share-gw
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-share-logs
      - name: mountroot
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-mountroot
      - name: share
        configMap:
          name: share
      - name: mounts
        configMap:
          name: mounts
      - name: webapps-share
        configMap:
          name: webapps-share
#      - name: keystore
#        persistentVolumeClaim:
#          claimName: {{ .Release.Namespace }}-keystore
      - name: keystore
        secret:
          secretName: ssl
      ### secrets
      - name: secret-files
        secret:
          secretName: secret-files
      ### localfiles
      - name: atb
        hostPath:
          path: /opt/mounts/030225/share/activiti-transitions-buttons-digital-signature.js
          type: File
      - name: atb-min
        hostPath:
          path: /opt/mounts/030225/share/activiti-transitions-buttons-digital-signature-min.js
          type: File
    metadata:
      labels:
        app: share
        name: {{ .Chart.Name }}-share
      annotations:
        vault.hashicorp.com/namespace: 'vault'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cauk-apps'
        vault.hashicorp.com/agent-inject-secret-config: 'ksed/cauk/app2'
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "ksed/cauk/app2" -}}
          export KERBEROS_SECRET=="{{ .Data.data.krb_PASS }}"
          {{- end }}`}}

